### PR TITLE
Stopify support for Klipse

### PR DESCRIPTION
**Pull request by rachitnigam**
Hey @viebel,
I've started working on stopping code execution inside Klipse snippets. Right now, I have a very basic implementation which simply ensure that scripts with infinite loops don't freeze the page (issue #162). 
In the code snippet below, I write an infinite loop in JavaScript but the page remains interactive. 
klipse

My final goal with this PR is to add a simple stop button on the top right corner of the klipse code snippet box that allows the user to stop execution of programs. Let me know if you have any other ideas/design goals you wanted to address with stopify.

### CODE REVIEW

**Comment by viebel** [comment]
Hey @rachitnigam.
I like what you did!

It would be a great idea to add a simple stop button on the top right corner of the klipse code snippet box that allows the user to stop execution of programs.

Please make it optional like all the other snippets and page settings. See `klipsify-with-opts` function and  the way we handle `eval_idle_msec` for instance.

The parameters can be set either at the level of the page or at the level of the snippet.

**Comment by rachitnigam** [comment]
Hi @viebel, sorry, got swamped with work in the last few months. I'll complete the PR in December when I'm on break. Thanks!

**Comment by rachitnigam** [comment]
Hey, this is the updated PR where all js-dbg.html works correctly. I've copied the stopify bundle in `resources/public` to make it easier to try it out. Once you verify it's working correctly, I can modify `common/resgistry` and `resource/public` to point to the right things.

**Comment by OvermindDL1** [comment]
Any work on this done int he past couple years?

**Comment by viebel** [comment]
@rachitnigam @OvermindDL1 It kinds of work but not perfectly.
The current state has been merged into master branch. See stopify-dbg.html for details.

**Comment by rachitnigam** [comment]
Tagging @arjunguha who is the current maintainer for Stopify and might be interested in this PR. I think the Stopify interface might also have evolved a bit since this PR so future updates should use those changes.

**Pull request closed without merging**
