### PR TITLE
Bower support

### PR DESCRIPTION
**Pull request by dvberkel**
This series of commits prepares this repository for bower support. The most notable changes are:

1. Track `klipse_plugin.min.js` in repository
2. Ignore everything but `README.md`, `LICENSE.txt`, `codemirror.css` and `klipse_plugin.min.js`

### CODE REVIEW

**Comment by viebel** [comment]
Thanks.
I've merged your PR.
Now, I'm trying to put all the binaries into the `dist` folder.
Note that we need both the minified and non-minified js - as minified js doesn't work with clojure.

**Comment by dvberkel** [comment]
@viebel I can help

The way bower works is that it takes your repository puts everything you do not ignore into an archive and ships that to the user. So just by creating a `dist` folder and *not* ignoring it explicitly should just work.

In case you are wondering, to my knowledge the `main` entry is only used for reference. It does not effect what gets packaged up.

**Comment by dvberkel** [comment]
For the record, there still a manual step to be made. I.e. [registering the package](https://bower.io/docs/creating-packages/#register)

All the prerequisites are in place, You only need to register step.

If you need help with that, let me now

**Comment by viebel** [comment]
@dvberkel I registered klipe on bower. 
Latest version is `3.1.5`.

Could you check it works fine for you?

**Comment by dvberkel** [comment]
I running

```sh
bower install klipse
```

Responded with 

```plain
bower not-cached    https://github.com/viebel/klipse.git#*
bower resolve       https://github.com/viebel/klipse.git#*
bower checkout      klipse#3.1.5
bower invalid-meta  The "main" field cannot contain minified files
bower resolved      https://github.com/viebel/klipse.git#3.1.5
bower install       klipse#3.1.5

klipse#3.1.5 bower_components/klipse
```

It retrieved the following files:

```plain
.
└── bower_components
    └── klipse
        ├── bower.json
        └── dist
            ├── codemirror.css
            ├── klipse_plugin.js
            └── klipse_plugin.min.js

3 directories, 4 files
```

Which is expected.

**Comment by viebel** [comment]
Great! Thanks for your contribution.

Please send me your slides when you have them - add them to the community
part of the README.md

**Comment by dvberkel** [comment]
No problem, thanks for creating klipse

I will send you my slides

**Pull request merged**
