### PR TITLE
Use relative, local URLs for fonts.

### PR DESCRIPTION
**Pull request by lechten**
Partially addresses issue #360.

### CODE REVIEW

**Comment by viebel** [comment]
Thanks for your PR @lechten 
The problem is that files under the dist folder are generated by this build script: https://github.com/viebel/klipse/blob/master/scripts/build#L16

You need to make your modifications in the build script.

**Comment by lechten** [comment]
The new commit applies the change to the source file that is copied in the build script.

**Comment by viebel** [comment]
The problem now is that the css is broken in the case where Klipse is not hosted locally.
The fix should be in the build script: replace the urls before copying codemirror.css to the dist folder

**Comment by lechten** [comment]
Ah, I hope this is what you had in mind.

**Comment by viebel** [comment]
That's exactly what I had in mind. 
Thank you for improving Klipse

**Pull request merged**
