### PR TITLE
Golang support using Yaegi

### PR DESCRIPTION
**Pull request by mliezun**
Issue [359](https://github.com/viebel/klipse/issues/359)
- Implemented golang support using [yaegi](https://github.com/traefik/yaegi)
- Golang code used to generate `yaegi.wasm`:

```go
package main

import (
	"bytes"
	"syscall/js"

	"github.com/traefik/yaegi/interp"
	"github.com/traefik/yaegi/stdlib"
)

func main() {
	idle := make(chan int)

	js.Global().Set("evalGo", js.FuncOf(evalGo))

	<-idle
}

func evalGo(this js.Value, inputs []js.Value) interface{} {
	stdout := bytes.NewBuffer(nil)
	stderr := bytes.NewBuffer(nil)

	i := interp.New(interp.Options{
		Stdout: stdout,
		Stderr: stderr,
	})

	i.Use(stdlib.Symbols)

	var errMessage string
	_, err := i.Eval(inputs[0].String())
	if err != nil {
		errMessage = err.Error()
	}

	return map[string]interface{}{
		"stdout": stdout.String(),
		"stderr": stderr.String(),
		"error":  errMessage,
	}
}
```
- Compiled with go 1.16: `$ GOOS=js GOARCH=wasm go build -o yaegi.wasm main.go`
- `wasm_exec.js` is a standard file got from `$ cp "$(go env GOROOT)/misc/wasm/wasm_exec.js"`
- Added `scripts-src-local` and `wasm-src-local` for local dev testing. (usage of these function should be changed before accepting PR)

### CODE REVIEW

**Comment by viebel** [comment]
Very good job @mliezun !
I cleaned up a bit the code in #394 and merged it to master.
Thank you.

**Comment by mliezun** [comment]
Great!
I found the blog post in Lobsters. Thank you for mentioning my contribution ✌️

**Comment by viebel** [comment]
My pleasure @mliezun 
Some people asked about the implementation details. Could you describe the process for compiling yaegi into WASM?

**Comment by mliezun** [comment]
Hi @viebel 
The explanation is in the first comment of this PR. You have the go code used and the command used to generate `yaegi.wasm` just underneath it.
If you never used go before it's easier to use go modules:
- Create new folder called `yaegi-js`
- Initialize module inside folder `$ go mod init yaegi-js`
- Copy go code to a new file called `main.go`
- Compile with `$ GOOS=js GOARCH=wasm go build -o yaegi.wasm main.go`
Let me know if you have any trouble running that or you need a more in depth explanation. Im happy to help.

**Pull request closed without merging**
