### PR TITLE
WIP: Add pyodide

### PR DESCRIPTION
**Pull request by alysbrooks**
Hi, Klipse looks neat, so I decided to try to add language support.

Klipse already has Python support via Skulpt, of course, but the advantage of Pyodide is that it supports a recent version of Python (3.8) and supports data science libraries like Numpy and Pandas.

This is a work-in-progress. Notably, code originally present on the page isn't evaluated after Pyodide finishes loading. I suspect there might be better ways to write the async code, as I don't have a lot of experience with `core.async.`.

### CODE REVIEW

**Comment by alysbrooks** [comment]
@viebel Once I fix the issue with the initial render/evaluation and clean up pyodide-dbg.html, is there anything I should do before this gets merged? Are you interested in adding pyodide support? If you prefer not to look at this PR until its out of draft status, that's cool too.

Another thing to maybe change is to add the pyodide.js file rather than pulling it from the CDN.

**Comment by viebel** [comment]
Hello @alysbrooks !
I am very interested in merging your PR.
Supporting  recent version of Python (3.8) and data science libraries like Numpy and Pandas would be terrific!

Could you add in the test page code that use features from:
1. Python 3.8 
2. Numpy
3. Pandas

**Comment by alysbrooks** [comment]
I added the examples you requested.

There could still be places the async code could be better, but I'm pretty happy with how it looks now.

Pyodide doesn't make it easy to capture things printed to console. My current approach works, but creates data races if multiple Klipse fields are evaluated close together. Their output will all go to the same global, and whichever field's callback gets to the global first will take the entire contents and then clear it.

**Comment by alysbrooks** [comment]
@viebel Right now the main limitation of the code as it stands is that capturing `print` doesn't work well with multiple Klipse fields.  I'm still hoping to fix that issue, but in case my ideas don't pan out, I'm wondering if it would be okay to merge this with the current limitation.

**Comment by alysbrooks** [comment]
@viebel I haven't had time to work on this, but I guess I'm still wondering if it would be okay to merge this with the current limitation, that capturing print doesn't work well with multiple Klipse fields.

**Comment by viebel** [comment]
I gave it a try today and I had an error when opening the pyodide test page

```
GET http://localhost:5014/pyodide.asm.js net::ERR_ABORTED 404 (Not Found)

**Comment by viebel** [comment]
Any update @alysbrooks ?

**Comment by alysbrooks** [comment]
@viebel Thanks for the reminder!

 I think I missed a `git add`. I'll try to push a commit with the missing file tonight.

**Comment by viebel** [comment]
@alysbrooks A kind reminder to commit the missing file

**Comment by alysbrooks** [comment]
@viebel thank you for the reminder! I actually misremembered; it's (currently) downloading from a CDN. I don't know what the issue you're having is, however.

**Comment by alysbrooks** [comment]
I cloned it into a fresh repository and ran `clj -A:figwheel --build dev`, and it seemed to work, too.

**Comment by viebel** [comment]
I found the issue. Only the initial pyodide JS file is loaded from the CDN.
I fixed it with this commit: https://github.com/viebel/klipse/commit/170d70b76e85eade15bc4ca2473a695e0685c36c

Now, we have a small issue: we need to find a way to make sure a code snippets is evaluated only after the previous ones are evaluated. 

It is required in order to be able to load a library in a code snippet and use it in a subsequent code snippet without loading the library again in the code of the subsequent code snippet. Take a look at the changes I made to the test page in this commit:  https://github.com/viebel/klipse/commit/01336484c852cb32aaa986fcf6c6d3decb8d9db5

**Comment by viebel** [comment]
@alysbrooks Thank you so much for adding pyodide support to Klipse!

**Pull request merged**
