### PR TITLE
Fix small typo

### PR DESCRIPTION
**Pull request by The-Alchemist**

### CODE REVIEW

**Comment by viebel** [comment]
Thanks @The-Alchemist 
What are your plans with Klipse?

**Comment by The-Alchemist** [comment]
I'm an educator, and so my interest is in using it as a tool to teach
JavaScript, and perhaps even extending it to support "quizzes" where you
need to have the right output to continue, a la code.org

**Comment by viebel** [comment]
I see. Let me know if you need help for the integration with klipse.
Are you interested only with javascript or also clojure and ruby?

**Comment by The-Alchemist** [comment]
Thanks, @viebel!  I might very well take you up on that.

JavaScript is my professional focus, but I have a personal interest in Clojure.

**Comment by viebel** [comment]
Keep me in the loop when you have something - even in draft mode.

**Pull request closed without merging**
