### PR TITLE
plugin: fix the empty line that was appearing at the end of input sni…

### PR DESCRIPTION
**Pull request by viebel**
…ppet

### CODE REVIEW

**Comment by KettuJKL** [comment]
Test like method definiton. 
(defn foo [x y] ...
Should be better naming.

**Comment by viebel** [comment]
@KettuJKL What do you mean?

**Comment by KettuJKL** [comment]
Method named "foo" is ok when testing things, but should be renamed when committed.

**Comment by viebel** [comment]
In this case, it's part of a "playground" test page.

**Comment by KettuJKL** [comment]
Oh. 
Then commit is ok. I'm bit embarrased. I need to improve my codebase reading skills. :-)

**Comment by viebel** [comment]
What is your interest about klipse?

**Comment by KettuJKL** [comment]
Just starting clojure coding and I'm just lopking through some commits to learn.

**Comment by viebel** [comment]
You should read my blog http://blog.klipse.tech

**Pull request merged**
